CREATE TABLE IF NOT EXISTS tickets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticketId TEXT UNIQUE NOT NULL,
  fullName TEXT NOT NULL,
  email TEXT DEFAULT '',
  phone TEXT NOT NULL,
  ticketType TEXT DEFAULT 'General',
  eventDate TEXT NOT NULL,
  qrToken TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'Active' CHECK(status IN ('Active','Used','Cancelled')),
  usedAt DATETIME,
  purchaseDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  visitorId INTEGER REFERENCES visitors(id)
);

CREATE TABLE IF NOT EXISTS visitors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  token TEXT,
  googleId TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  token TEXT
);
